stages:
  load_data:
    cmd: python src/data.py
    deps:
    - config/main.yaml
    - data/raw
    - src/data.py

  train:
    cmd: python src/train_model.py
    deps:
    - config/main.yaml
    - data/processed
    - src/train_model.py
    outs:
    - models/log_reg.joblib

  test:
    cmd: python src/test_model.py
    deps:
    - config/main.yaml
    - data/processed
    - models/log_reg.joblib
    - src/test_model.py
    metrics:
    - metrics/log_reg_metrics.json
