stages:
  load_data:
    cmd: python src/data.py
    deps:
      - config/main.yaml
      - data/raw
      - src/data.py

  preprocess_data:
    cmd: python src/process.py
    deps:
      - config/main.yaml
      - data/raw/input.csv
      - data/raw/output.csv
      - src/process.py
    outs:
      - data/processed/train_features.csv
      - data/processed/test_features.csv
      - data/processed/train_labels.csv
      - data/processed/test_labels.csv
      - models/scaler.joblib

  train:
    cmd: python src/train_model.py
    deps:
      - config/main.yaml
      - data/processed
      - src/train_model.py
    outs:
      - models/log_reg.joblib

  test:
    cmd: python src/test_model.py
    deps:
      - config/main.yaml
      - data/processed
      - models/log_reg.joblib
      - src/test_model.py
    metrics:
      - metrics/log_reg_metrics.json
